fix: change `publish` to use http relay client in handlers
WalletConnect/notify-server pull request #142
Opened 2023-10-23 21:08 UTC by geekbrother

# Description

This PR changes the use of `publish` from websocket client to the HTTP relay client to solve the websocket disconnect issue.

Resolves #74

## How Has This Been Tested?

**Draft TBD**

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

2023-10-23 22:57 UTC, chris13524 requested changes
Don't we need this for the `/notify` endpoint too?

2023-10-24 10:52 UTC, geekbrother commented
> Don't we need this for the `/notify` endpoint too?

I think not because we are already using the HTTP relay client [when processing publishing jobs](https://github.com/WalletConnect/notify-server/blob/8e0bd48a725785a0c3276fa6193c79cb18463424/src/handlers/notify.rs#L124).

2023-10-24 12:59 UTC, chris13524 requested changes

2023-10-24 12:59 UTC, chris13524 commented on .github/workflows/sub-validate.yml
> +          ref: 'develop'
Can you revert this change?

2023-10-24 13:09 UTC, geekbrother commented on .github/workflows/sub-validate.yml
> +          ref: 'develop'
Sure, it's done.

2023-10-24 13:14 UTC, chris13524 approved these changes

2023-10-24 19:30 UTC, merged